name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Build
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: .github/workflows/build_release.sh

      - name: Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65
        with:
          files: |
            bindgen_darwin_amd64.tar.zst
            bindgen_darwin_arm64.tar.zst
            bindgen_linux_amd64.tar.zst
            bindgen_linux_arm64.tar.zst
            bindgen_windows_amd64.tar.zst
            bindgen_windows_arm64.tar.zst
            SHA256.txt
